application: ml-training-backup
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /scripts
  static_dir: scripts

- url: .*
  script: training.application

libraries:
- name: webapp2
  version: latest
