N_ACTIVITIES = 6
N_RINGER_MODES = 3
# 0 - WORK HOUR, 1 - OTHER
N_HOUR = 2
# 0 - AM , 1 PM
N_AM_PM = 2
# 0 - WEEKDAY, 1 - WEEKEND
N_DAY_OF_WEEK = 2
N_BIAS = 1

N_DIMENSIONS =  N_ACTIVITIES + N_RINGER_MODES + N_HOUR + N_AM_PM + N_DAY_OF_WEEK + N_BIAS