application: realtnews
version: 1
runtime: php
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /.*
  script: new.php
